---
title: "Homer Github Theme"
subtitle: "Tim0-12432"
logo: "logo.png"

header: true
footer: '<p>Theme made with <span class="has-text-danger">❤️</span> by <a href="https://github.com/tim0-12432">Timo</a></p>' # set false if you want to hide it.

stylesheet:
  - "assets/gh-theme.min.css"

columns: "2"
theme: default

message:
  style: "is-dark"
  title: "Demo !"
  icon: "fa fa-grin"
  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/tim0-12432/homer-github-theme"
    target: "_blank"
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
    target: "_blank"

services:
  - name: "GitHub"
    icon: "fab fa-github"
    items:
      - name: "Github"
        icon: "fab fa-github"
        subtitle: "The github repo for this theme"
        tag: "github"
        tagstyle: "is-primary"
        url: "https://github.com/tim0-12432/homer-github-theme"
        target: "_blank"

  - name: "Reddit"
    icon: "fab fa-reddit"
    items:
      - name: "Just Reddit"
        icon: "fab fa-reddit"
        tag: "reddit"
        tagstyle: "is-info"
        url: "https://www.reddit.com/r/selfhosted"
        target: "_blank"

  - name: "Other"
    icon: "fas fa-ellipsis-h"
    items:
      - name: "Google"
        icon: "fab fa-google"
        subtitle: "Google is a nice search engine"
        tag: "google"
        tagstyle: "is-danger"
        url: "https://www.google.com"
        target: "_blank"
        type: "Ping"
        endpoint: "https://www.google.com"
