name: Build for release

on:
  workflow_dispatch:

jobs:

  lint:
    name: Lint CSS files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
      working-directory: ./utils
    - name: Run linter
      run: npm run lint
      working-directory: ./utils
    - id: appVersion
      run: echo "VERSION=$(cat VERSION.txt)" >> $GITHUB_OUTPUT
    - name: Upload reports to artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: reports-v${{ steps.appVersion.outputs.version }}
        path: |
          linting-report.txt

  build:
    name: Build CSS files
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
      working-directory: ./utils
    - name: Run minifier
      run: npm run minify
      working-directory: ./utils
    - name: Cache CSS
      uses: actions/cache@v3
      with:
        path: |
          assets/gh-base.min.css
          assets/gh-dimmed.min.css
          assets/gh-light.min.css
          assets/gh-dark.min.css
        enableCrossOsArchive: true
        key: mincss-${{ hashFiles('assets/gh-base.css','assets/gh-dark.css','assets/gh-dimmed.css','assets/gh-light.css') }}
        restore-keys: |
          mincss-

  release:
    name: Create release
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Load minified CSS
      uses: actions/cache@v3
      with:
        path: |
          assets/gh-base.min.css
          assets/gh-dimmed.min.css
          assets/gh-light.min.css
          assets/gh-dark.min.css
        enableCrossOsArchive: true
        fail-on-cache-miss: true
        key: mincss-${{ hashFiles('assets/gh-base.css','assets/gh-dark.css','assets/gh-dimmed.css','assets/gh-light.css') }}
        restore-keys: |
          mincss-
      id: cache-css
    - id: appVersion
      run: echo "VERSION=$(cat VERSION.txt)" >> $GITHUB_OUTPUT
    - name: Upload files to artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: files-v${{ steps.appVersion.outputs.version }}
        path: |
          assets/gh-base.min.css
          assets/gh-dimmed.min.css
          assets/gh-light.min.css
          assets/gh-dark.min.css
          assets/config.yml
          README.md
          VERSION.txt
          LICENSE.md
    - name: Upload binary to release
      uses: softprops/action-gh-release@v1
      if: steps.cache-css.outputs.cache-hit == 'true'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_unmatched_files: true
        generate_release_notes: true
        tag_name: v${{ steps.appVersion.outputs.version }}
        name: v${{ steps.appVersion.outputs.version }}
        files: |
          assets/gh-base.min.css
          assets/gh-dimmed.min.css
          assets/gh-light.min.css
          assets/gh-dark.min.css
          assets/config.yml
          README.md
          VERSION.txt
          LICENSE.md
